### auth
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "login": "admin",
  "password": "admin"
}

> {%
    client.global.set("auth_token", response.body.accessToken);
%}


### Create product
POST http://localhost:8080/product
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "productName": "new",
  "description": "string",
  "price": 190,
  "picture": "string",
  "categoryId": "ffea6677-4519-45e3-a679-2d94106eaa5d",
  "status": 1
}


### create user
POST http://localhost:8080/user
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "login": "user",
  "userRole": "USER",
  "password": "user"
}

### delete user
DELETE http://localhost:8080/user/e2f3c4ec-b543-414b-a0e8-c33e6c824feb
Authorization: Bearer {{auth_token}}

### update user
PUT http://localhost:8080/user/e2f3c4ec-b543-414b-a0e8-c33e6c824feb
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "login": "newUser",
  "userRole": "ADMIN",
  "password": "string"
}




### update product
PUT http://localhost:8080/product/c0d54136-efdb-4ab9-bd02-402531edf5e5
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "productName": "newPr",
  "description": "string",
  "price": 100,
  "picture": "string",
  "categoryId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "status": 0
}


### delete product
DELETE http://localhost:8080/product/9c52d100-6f5f-4df0-a357-503bdc7768dd
Authorization: Bearer {{auth_token}}

### find product by criteria
GET http://localhost:8080/product?category=lalalal&low-price=1



### create category
POST http://localhost:8080/category
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "category": "jhfehuiehe",
  "description": "string"
}


### delete category
DELETE http://localhost:8080/category/681d4737-7bc0-4f50-8791-e221f0179ef8
Authorization: Bearer {{auth_token}}


### update category
PUT http://localhost:8080/category/1a5f52d7-646b-4155-900b-d1f6ded100fc
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "category": "lalalal",
  "description": "twtetew"
}



### find category by name
GET http://localhost:8080/category?category=jhfehuiehe
Authorization: Bearer {{auth_token}}





